// <auto-generated />
using System;
using BackPuppy.Entity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BackPuppy.Migrations
{
    [DbContext(typeof(AplicationDbContext))]
    [Migration("20230612035354_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BackPuppy.Entity.persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("apellidoMaterno")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("apellido_materno");

                    b.Property<string>("apellidoPaterno")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("apellido_paterno");

                    b.Property<string>("api_estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("api_transaccion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("carnet")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("carnet");

                    b.Property<int>("celular")
                        .HasColumnType("integer");

                    b.Property<string>("correo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("direccion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("fecha_cre")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("fecha_mod")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("nombres")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("usuario_mod")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("personas", "public");
                });
#pragma warning restore 612, 618
        }
    }
}
